### ISSUE TITLE
Commits qui traînent dans le dépôt d'hadware.

### ISSUE THREAD

**Issue by PrFeurisson** [loult-elte-fwere/loult-ng#1]
Faudrait que tu remettes à zéro ton dépôt, il y a toujours les commits de la tentative du subtree qui reviennent dès que tu merge un truc. ~~Tu les as d'ailleurs envoyé à nouveau dans le dépôt de 4577 alors que je les avais retiré, va falloir expliquer à mrle qu'il faut qu'il remette lui aussi le dépôt à zéro car là c'est le bordel complet.~~

**Comment by hadware** [comment]
Mais ça pose quoi comme problème concret que ces commits à la con traine dans le dépot? Je veux dire, ai-je réellement besoin de faire un rebase si ça pose pas de problèmes?

**Comment by PrFeurisson** [comment]
Car sinon ton prochain commit va les faire revenir.

**Comment by hadware** [comment]
Ouee mais du coup faut je rebase sur quel dépôt+branche idéalement ?

**Comment by hadware** [comment]
Et en dehors de salir l'historique, si j'ai bien compris, on s'en tape nan?

**Comment by PrFeurisson** [comment]
J'ai déjà eu des pbs avec des outils qui s'attendent pas à deux commits racines, et ça rend l'historique moins compréhensible.

**Comment by hadware** [comment]
Et du coup pour la branche?

**Comment by PrFeurisson** [comment]
T'as une branche qui dépend de ces commits ?

**Comment by hadware** [comment]
Nonnww

**Comment by PrFeurisson** [comment]
Donc tu peux revenir à un vieux commit et pull depuis ce dépôt.

**Comment by hadware** [comment]
Okèw
