### ISSUE TITLE
Shadowban

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#10]
Un nouveau type de ban qui ne déconnecte pas le mec ni rien, mais qui fait que le python arrete tout simplement de traiter / broadcast ses messages, ou idéalement ne les renvoie qu'à lui meme. Donc quand le shadowbanni parle, de son point de vue tout est normal (sauf que personne lui répond xd) mais pour tout le reste, il a juste l'air afk.

**Comment by hadware** [comment]
déjà fèw. Reste plus que j'te pwlepwle le truc, et faudra que tu rajoutes une commande à ton interface de ban, j'texpliquerai dans le pwlepwle c'est quoi qu'il faut mettre dans le JSON pour que ça marche (c'est relativement similaire à des JSON de ban habituels).

**Comment by LePetitMarill** [comment]
Cimer chef
