### ISSUE TITLE
Message audio

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#11]
We, donc l'idée à la base était qu'on puisse envoyer un message normal, comme un type "msg", sauf que c'est un type "audio" (ou whatever hein) et que ça ne broadcast que la voix aux autres, pas le texte. Donc renvoyer juste le résultat audio avec effets éventuels mais pas de texte. A la base c'était pour des cookies modo ou faire des vannes genre balancer du vieux mémé du terroir avec un cookie qui va bien. We?

A noter que vu l'état de gangrène avancé de la communauté actuellement ce n'est pas du tout une urgence :^)

**Comment by hadware** [comment]
ouai izi ça, il suffit juste de rajouter un tag sur le json du message genre "audio_only=true" et c'est bon. Après il suffit de rajouter une commande genre "/blind wswoiw" coté client pour que ça fonctionne.

> A la base c'était pour des cookies modo ou faire des vannes genre balancer du vieux mémé du terroir avec un cookie qui va bien. We?
J'ai pas capté de ouf le contexte dans lequel ça pourrait servir tho

**Comment by LePetitMarill** [comment]
Ben shaipaw

Un fantome de qwilfish?
