### ISSUE TITLE
Délais avant le premier message

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#15]
Aouee un oubli, mais ce serait bien que tout message envoyé 10/20/30? sec après la connexion soit ignoré. Pour empecher les vagues de flood de random qui se co / poste / déco et font crash le site ^^ :p xD

**Comment by hadware** [comment]
ouee. Pas duw à fèw çaw. Jpeux le mettre en prioritèw.

**Comment by LePetitMarill** [comment]
Ce serait pas mal, c'est une des dernières grosses "failles" je crois.
Dans l'absolu faudrait aussi limiter le nombre de connexion / ip / minute, c'était fait en théorie dans nginx mais apparemment ça ne marche pas xd
T'as moyen de bloquer les connexions coté py aussi ? Un peu de la meme façon
