### ISSUE TITLE
Fix bug Webaudio Chrome

### ISSUE THREAD

**Issue by hauntedfnre** [loult-elte-fwere/loult-ng#18]
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Last Chrome update fucked with the loult. :gun:

**Comment by hadware** [comment]
peuw

**Comment by haspagan** [comment]
> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

c t donc sa

**Comment by haspagan** [comment]
En clair, au chargement de la page, aucun son n'est émis tant que l'utilisateur n'a pas interagit avec : Clic, focus d'un input, etc. Ça arrive donc par exemple de se prendre des dizaines de messages audio d'un coup dans la gueule dans les heures les plus actives

**Comment by haspagan** [comment]
Proposition : Un simple overlay conditionnel pour les utilisateur de chrome/chromium qui se désactive par un clic, pour signaler que le son est mute (l'autoplay est desactivé)

**Comment by haspagan** [comment]
Je n'avais pas vu le commit c4993f64e4016bec890100926df23e98fdeed97e de @hauntedfnre :man_facepalming: Aussi j'ouvrirai une autre issue pour un l'overlay suggéré plus haut, puisque le bug en question est déjà corrigé depuis bien longtemps
