### ISSUE TITLE
Fix de l'interface de config utilisateur

### ISSUE THREAD

**Issue by hadware** [loult-elte-fwere/loult-ng#24]
Le texte de a fenêtre de config dépasse, il faut réparer sa !!!

**Comment by hadware** [comment]
Aussi, la config d'ossa est pas permanente, à réparer aussi.

**Comment by OssaLeBibw** [comment]
Pouvons nous avoir une capture d'écran du bug ?

**Comment by hadware** [comment]
![image](https://user-images.githubusercontent.com/5477031/65965159-6db2bd80-e45e-11e9-83b6-eb21aae58f0d.png)

Dans la foulée faudrait faire une page statique pour les règles, intégrée au loult, genre sur loult.family/static/rules.html

**Comment by haspagan** [comment]
Ajout de la charte / règles

#e46777b6fb3cdab6be2c6c005c5fb95199c398a6

CSS menu configuration

#b1bbacb578bb742f35edf18196c4e9d1a0877932
