### ISSUE TITLE
Interface Objet

### ISSUE THREAD

**Issue by OssaLeBibw** [loult-elte-fwere/loult-ng#28]
L'ajout d'une interface pour les objets accessible par /list et /bank.

N'ayant rien compris au projet j'essaye de résumer l'idée :

-Afficher les items disponibles dans la banque et dans l'inventaire par des miniatures d'objet.
-Recup objet de la banque en cliquant dessus.
-Permettre d'utiliser un objet (aucune idée de comment l'utilisateur cible doit être choisi(un overlay qui apparait lorsqu'on sélectionne l'objet ?) )   

J'imagine un coffre qui lorsqu'il est surpassé par le curseur de souris ou cliquer (préférable pour version mobiles)  affiche  en dessous de la liste des utilisateurs les objet de la banque et de son inventaire personnel.

Il me semble qu'il n'y a pas de nouveau message envoyer avec websocket lorsqu'un nouvel objet s'ajoute a la banque, il faudra ajouter une boucle coté client(js) qui check chaque seconde la banque ou alors envoyer un json depuis serveur lorsqu'un nouvel objet est dispo

**Comment by hadware** [comment]
Eh bien vous voilà fort sérieux Mr le Bibw.

En effet y'a quelques questions que j'ai pas totalement élucidé encore, vu que y'a des objets qui s'utilisent juste sans paramétrage (genre la couronne) et d'autres qui s'utilisent "sur un utilisateur". Y'a aussi des objets que j'ai pas encore fait qui s'utiliseraient avec un paramétrage qui n'est pas forcément un utilisateur visé (par exemple un objet pour se renommer soit-même)

idéalement oui les objets de l'inventaire s'utilisent
- soit avec un double clic, et ceux qui s'appliquent à un utilisateur s'appliqueraient avec un drag-n-drop
- soit avec un menu contextuel spécial sur lobjet (clic droit -> utiliser ou clic droit -> utiliser sur...)

Pour la banque, pareil, un drag'n'drop ou un menu contextuel. 

Le problème c'est les objets avec un (ou des) paramètres textuels qui sont pas des utilisateurs. Là du coup il faudrait paramétrer le JSON de l'objet pour indiquer au client que l'objet nécessite des paramètres rentrés par l'utilisateurs, et client génèrerait alors un menu en popup (ou autre chose, je sais pas) qui permettrait à l'utilisateur de rentrer ses paramètres.

A noter que ce genre de fonctionnement, en paramétrant tout en JSON et plus avec des entrées textes, simplifierait considérablement certaines parties du code.

Aussi, à noter qu'actuellement tout les échanges se font via le websocket qui est un peu un gros évier dans lequel tout termine, j'aimerait que ledit websocket soit réservé uniquement aux échanges de texte et de son, et que tout le reste se fasse via une API RESTful... Du coup (et ça serait pour une autre issue), une interface en Sanic ou en Quart serait bienvenue pour passer tout ça sur du RESTful

**Comment by hadware** [comment]
aussi, voilà les icônes fabriquées par les petites mains de Mr Ossa
[LOULT INVENTAIW.zip](https://github.com/loult-elte-fwere/loult-ng/files/3718947/LOULT.INVENTAIW.zip)

**Comment by OssaLeBibw** [comment]
j'ai fini pour la partie front,
J'ai remarqué que les images n'ont pas le meme nom que dans le json ou alors n'existe pas, ça fonctionnera pas et affichera un icone image non trouvé.

Je n'ai pas essayé avec la modification du json (je suis certain qu'il faudra refaire une petite mise a jour du code)

**Comment by OssaLeBibw** [comment]
var chest= document.getElementsByClassName("icon")[0];

showInventory=false,
showBank=true;

class itemHandler {

        // adjustUserlistHeight=()=>{
        //      userlist.style.height=`calc(100% - ${item.offsetHeight+10}px)`
        // }

        ////
        displayBank=()=>{

            // if(showBank)bankContainer.style.display="block";
            // else bankContainer.style.display="none";
            // this.adjustUserlistHeight();
        }

        displayInventory=()=>{
            // if(showInventory)inventoryContainer.style.display="block";
            // else inventoryContainer.style.display="none";
            // this.adjustUserlistHeight();
        }

        RefreshItemBank=(items)=>{

            // bankContainer.removeChild();
            // for(let a=0;a>items.length;a++){

                // let divimg = document.createElement("div"); 
                // let img = document.createElement("img"); 
                // // img.src="/img/inventory/"+items[a]+".gif";
                // img.src="/img/inventory/link.gif";
                // divimg.appendChild(img);
                // bankContainer.appendChild(divimg);
            // }
                // this.adjustUserlistHeight();

        }

        RefreshItemInv=(items)=>{
            let bulle=document.getElementById("inventaireDiv");

            // inventoryContainer.removeChild();
            // for(let a=0;a>items.length;a++){
                let divimg = document.createElement("div"); 
                let img = document.createElement("img"); 
                // img.src="/img/inventory/"+items[a]+".gif";
                img.src="/img/pokemon/small/030.gif";
                divimg.appendChild(img);
                bulle.appendChild(divimg);
    

        }

        createItemWindow=()=>{
            const bulle=document.createElement('div');
            bulle.id="inventaireDiv";
            bulle.style.position="absolute";
            bulle.style.display="none"; 

            const bullePique=document.createElement('div');
            bullePique.id="bullePique";
            bullePique.style.position="absolute";
            bullePique.style.display="none"; 

            document.body.appendChild(bullePique);
            document.body.appendChild(bulle);

            chest.addEventListener("click", ()=>{
                bulle.style.display="block"; 
                showInventory=!showInventory;

            //test
            this.RefreshItemInv();
            //test
            });

            chest.addEventListener("mousemove", function(e) {

                // sourisY - HauteurBulle - 1/2(HauteurBulle)
                bulle.style.top=event.clientY-bulle.offsetHeight-bullePique.offsetHeight/2 +"px";


                bullePique.style.top=bulle.offsetTop+bulle.offsetHeight-(bullePique.offsetHeight/1.25) +"px";


                // sourisX - LargeurBulle - 25%(LargeurBulle)
                bulle.style.left= event.clientX-(bulle.offsetWidth-0.25*bulle.offsetWidth ) +"px";

                bullePique.style.left=bulle.offsetLeft+bulle.offsetWidth*0.65 +"px";
            });

            chest.addEventListener("mouseenter", ()=>{
                bulle.style.display="block"; 
                bullePique.style.display="block"; 

                bullePique.style.top= bulle.offsetHeight - 0.75*bullePique.offsetHeight+'px';
            });

            chest.addEventListener("mouseleave", ()=>{
                if(!showInventory)bulle.style.display="none"; bullePique.style.display="none"; 
            })
        }
        initItem=()=>{
                this.createItemWindow();

            }
}
https://mongoloult.tk/

**Comment by hadware** [comment]
@haspagan check ça

**Comment by haspagan** [comment]
J'avais pas fait attention à cette issue, aussi je n'ai capté le nouveau code sur mongoloult que très tardivement, l'idée de la bulle qui se place à la position du curseur est pas mal mais rend plus compliqué la réalisation d'un inventaire utilisable. L'issue #43 est un doublon donc

**Comment by OssaLeBibw** [comment]
Caratroc n'aimait pas la bulle qui se place a la position du curseur il veut un truc statique

**Comment by hadware** [comment]
Je suis plus adepte du bail statique aussi.

**Comment by haspagan** [comment]
J'ai poussé une séries de commit pour une première version d'un menu d'inventaire, j'ai pisté quelques petits glitchs mais les bases sont là :

f55490a9b78fcc96ebe9b16296719845a796f364
b13bad0e628bed8236baad44a8a009af0a600fc0

A chaque mouseover la position de l'inventaire est recalculée à partir de la taille de celui-ci et de la position du coffre.

**Comment by haspagan** [comment]
Bonjour,

On a système d'objet globalement fonctionnel, les améliorations et nouvelles fonctionnalités devraient être traitées via des issues isolées.
