### ISSUE TITLE
Pokéflûte

### ISSUE THREAD

**Issue by Cofondateuw** [loult-elte-fwere/loult-ng#39]
Wjouw les bibw !

Quand on clique sur la Pokéflûte, ça devrait générer cette image :

![ronflex fisté](https://user-images.githubusercontent.com/56731617/67104576-7a0d7900-f1c7-11e9-8a23-fbfd2995c8e8.png)

Bien cordialement,

Cofondateuw

**Comment by OssaLeBibw** [comment]
Je propose une option caché pour activé cette fonctionnalité

**Comment by haspagan** [comment]
@Cofondateuw  I'm so used to people acting professional on github I'd rather not see comments like that here.
