### ISSUE TITLE
Script d'installation voix mbrola ko

### ISSUE THREAD

**Issue by haspagan** [loult-elte-fwere/loult-ng#42]
Bonjour à toute l'équipe de développement de ce site web.

Le lien qui sert à récupérer les voix mbrola est ripw (code 502), rendant impossible l'installation automatisée des voix via le script voices_install.py.

C'est peut-être temporaire.

Le lien suivant peut servir de base pour la correction du script, en sachant que l'archive avec toutes les voix est volumineuse.
https://github.com/numediart/MBROLA-voices/tree/master/data

_Happy hacking._

**Comment by hadware** [comment]
yes il faut que je le réparennww. Faut que je fasse ça sur voxpopuli

**Comment by hadware** [comment]
Je l'ai réparé sur le dépot de voxpop, je vais faire une modif dans la logique des objets de voxpopuli et je push une nouvelle version sur pypi.
