### ISSUE TITLE
Cooldown sur certain objets

### ISSUE THREAD

**Issue by haspagan** [loult-elte-fwere/loult-ng#51]
Bonjour,

Quelques objets peuvent servir à _certains_, de part l'absence de cooldown, à spammer le chat de messages impossibles à muter.

Comme la solution existe déjà et qu'elle est triviale à mettre en place mais que je suis seulement capitaine de mon propre bateau, je vas faire une branche qui corrige ça, à merger si c'est ok

**Comment by haspagan** [comment]
dans gitlab on peut créer une branche remote associée à une issue via l'interface de l'issue en question, rep à ça github

**Comment by haspagan** [comment]
Commit concerné fa86d00feeed027c70085ce8b6b5a4fc1c651a34

merci aux programmateurs de code de faire leur travail.

**Comment by hadware** [comment]
Merciw c'est gentiw.

**Comment by haspagan** [comment]
sa marche pa

**Comment by Cofondateuw** [comment]
Flpe a supprimé les items qu'on peut spam pour régler le problème, isw

![image](https://user-images.githubusercontent.com/56731617/68530084-58ef0280-0305-11ea-9c9c-87443ed3cc1a.png)

**Comment by haspagan** [comment]
nickel merci

**Comment by hadware** [comment]
dans la branche `objects-api-refactor`, la plupart des objets qui devraient avoir un cooldown en ont un. J'ai rajouté un système de décorateurs pour que ça se fasse plus simplement.

**Comment by haspagan** [comment]
Ok parfait, j'ai pas vu cette nouvelle branche, hésite pas à fermer l'issue une fois que tu en as terminé avec cette branche (ou à référencer l'issue dans le(s) commit(s))

**Comment by hadware** [comment]
je pense que tout les objets nécessitant des cooldown ont été cooldowné
