### ISSUE TITLE
LoultMail

### ISSUE THREAD

**Issue by OssaLeBibw** [loult-elte-fwere/loult-ng#52]
Je propose dans la suite de Loultshack de crée un service de webMail pour loult avec un serveur smtp et pop
un serveur de mail qui écoute sur le port TCP 25 pour faire de l'email marketing

nous pouvons utiliser des outils turboSMTP pour permettre de configurer un service qui ma foi est tres compliqué a mettre en place 

j'imagine déja les adresses du genre: 
Marill@loult.family
ossatueur@loult.family
crysw@loult.family
Cofondateuw@loult.family
sblte@loult.family

**Comment by haspagan** [comment]
loult.onion
