### ISSUE TITLE
Lien du vieux repo dans le menu

### ISSUE THREAD

**Issue by haspagan** [loult-elte-fwere/loult-ng#57]
Bonjour,

Le lien vers la page Github du projet mène toujours vers le dépot initial (4577/loult-ng), qui n'est plus maintenu depuis 2 ans, plutôt que ce dépot là, autour duquel s'organise le développement et la signalisation de bug via les issues.

Si ça n'est pas un choix délibéré, on peut mettre à jour le lien, au moins pour que les utilisateurs *puissent* signaler les problèmes

Bon travail

**Comment by hadware** [comment]
Ben we c'est carrément une erreur. A changer au plus vite cher kaniw.

**Comment by haspagan** [comment]
Ok ça marche, on va corriger ce bug critique
