### ISSUE TITLE
Mute instantané d'un utilisateur

### ISSUE THREAD

**Issue by haspagan** [loult-elte-fwere/loult-ng#60]
Bonjour,

Vieux problème : Le mute d'un utilisateur n'est effectif qu'à la fin de la lecture du dernier message posté avant le mute. Normalement ça doit être possible de couper le son tout suite coté client grâce à l'api audio de javascript. Précisez ici si jamais des modifications coté serveur sont requises

https://developer.mozilla.org/en/docs/Web/API/Web_Audio_API/Using_Web_Audio_API

Bon travail

**Comment by hadware** [comment]
De ce que j'avais plus ou moins recherché à l'époque, faudrait lancer un lecteur audio par utilisateur, et muter sélectivement chacun des lecteurs.

**Comment by haspagan** [comment]
Oui c'est ça, ça me revient, à voir si ça n'est pas trop gourmand en ressources

**Comment by haspagan** [comment]
L'idée c'est d'associer les buffets audio avec les id d'utilisateurs (ou ceux des événements) et de les supprimer après lecture complète ou après un arrêt prématuré (le fatal *mute*). C'est une mesure passive pour le flood et ponctuelle pour les messages audio trop longs qu'on voudrait abréger en deux clics, par exemple

**Comment by haspagan** [comment]
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at AudioBufferSourceNode.source.onended (script.js:974)
```

c'est fragile, l'équipe se charge de ça

**Comment by hadware** [comment]
Résoluw
