### ISSUE TITLE
Vocaroo ne fonctionnent plus

### ISSUE THREAD

**Issue by goupixlareine** [loult-elte-fwere/loult-ng#61]
Bonjour,

Avec la mise a jour de Vocaroo le loult n'est plus compatible avec le nouveau vocaroo y compris les anciens liens qui ont changé de vocaroo pour oldvocaroo. Vous pensez qu'il y aurais moyen de régler ça ?

Merci et a bientôt

**Comment by haspagan** [comment]
Bien noté, merci pour le retour, on va regarder ça

**Comment by haspagan** [comment]
Corrigé via les deux commits suivants :
+ filter for the new vocaroo urls scheme : 1215d4270b2edb82a679497e77c5e9314c835aa0
+ adding filter for the now old version of vocaroo : 379b8b2

@hadware à déployer quand tu peux
