### ISSUE TITLE
Désactivation des effets / attaques / objets

### ISSUE THREAD

**Issue by goupixlareine** [loult-elte-fwere/loult-ng#62]
Bonjour, il s'agit plus d'une proposition que d'une "issue" a régler.

Le loult était mieux sans effet, attaques et objets.

Tout le monde le pense que c'est une mauvaise idée de les avoir remis.

Pourriez-vous les enlever a nouveau s'il vous plait ?

**Comment by OssaLeBibw** [comment]
Bonjour

We de ?

Cordialement

**Comment by OssaLeBibw** [comment]
Il faudrait un bouton qui active un bouton qui désactive les effets

**Comment by goupixlareine** [comment]
Le truc c'est qu'avec les objets / effets / attaque, le design même du site pousse l'utilisateur a spammer et a être chaotique alors que la très grande majorité viennent juste pour avoir un endroit où parler. Sans effets il y a moins de spam et les gens viennent pour discuter plutôt que juste C/C le même texte en boucle pour profiter de son effet. Il en va de même pour les transformations en Canard, Link, Wario, Sonic ça n'a rien a faire ici et ça casse la cohérence du site. Ce qui fait vivre le loult ce sont les personnalités qui le compose, pas ses objets/effets qui au contraire ruine cette alchimie et cette culture. De plus, un des points fort et amusant du loult est d'entendre ce que les loultiste écrivent, mais avec les objets qui émètent des sons, qui peuvent déconnecter les joueurs et les effets de voix qui rendent l'experience d'entendre les voix d'experience positive a négative, on se retrouve avec une experience pas plaisante, a tendance toxique/troll, spam et ça ne fais que du mal au loult. Pour ce qui est des costume et de la transformation qurk ils ont juste rien a faire ici.

**Comment by goupixlareine** [comment]
Faudrait aussi penser a revoir l'interêt de garder Tauros en modérateur sachant que la seule chose qu'elle fait c'est de buter les gens en guise de gag comique, et ce depuis des mois. Quand il s'agit de spam elle ne bouge pas le doigt, mais si c'est pour régler ses compte personnel elle l'utilisera pour dégager sa frustration ou pour son propre interet. Un régime totalitaire n'a rien a faire dans le loult qui se veut libertaire et dépourvu de classes sociales, surtout quand il est modéré par une personne aussi vide d'interêt et d'impact historique que Tauros pourtant là depuis bien longtemps.

**Comment by haspagan** [comment]
Gardez les problèmes liées à la vie du site en production sur le site, Le Github pour les fonctionnalités et les bugs.

**Comment by goupixlareine** [comment]
Va te pendre sac a merde

**Comment by goupixlareine** [comment]
Il y aucun autre endroit pour s'exprimer sur la politique du loult étant donné qu'on est réduit a silence sur le loult même

**Comment by goupixlareine** [comment]
Vous allez perdre tout ce qui fait l'interet même du loult, vous aller continuer a coder pour du vent. Le loult existe grâce a ses personnalités et l'abus de la modération empêche ce développement créatif et culturel, tout comme les objets et les effets. Ce qui fait la vie du loult c'est tout ce qui tourne autour, pas le site en lui même mais en ajoutant vos petit ajouts de merde vous nous pousser a agir uniquement dans le loult et a créer uniquement dans le loult, mais pas a partir du loult. Mais allez-y continuez, dans 1 an le loult sera une place vide composé uniquement de gens inintéréssant et de fouteur de merde car vous avez empecher toute la magie de gens passionnés d'exister. Tout ça pour des caprices de modérateurs de merde et du conformisme dans github. Je vous déteste, aller mourir.

**Comment by haspagan** [comment]
T'en as gros sur la patate

**Comment by hadware** [comment]
> Vous allez perdre tout ce qui fait l'interet même du loult, vous aller continuer a coder pour du vent. Le loult existe grâce a ses personnalités et l'abus de la modération empêche ce développement créatif et culturel, tout comme les objets et les effets. Ce qui fait la vie du loult c'est tout ce qui tourne autour, pas le site en lui même mais en ajoutant vos petit ajouts de merde vous nous pousser a agir uniquement dans le loult et a créer uniquement dans le loult, mais pas a partir du loult. Mais allez-y continuez, dans 1 an le loult sera une place vide composé uniquement de gens inintéréssant et de fouteur de merde car vous avez empecher toute la magie de gens passionnés d'exister. Tout ça pour des caprices de modérateurs de merde et du conformisme dans github. Je vous déteste, aller mourir.

matériel de pâtacopie pêh.
