### ISSUE TITLE
Saloper les cookies en cas de ban

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#7]
Merci pour l'ajout du type "banned" qui permet le mindgame évoqué il y a quelques temps, mais, il faudrait pouvoir choisir si on l'envoie à un mec ou pas. Le but de cette technique est de pourrir la vie de l'utilisateur en lui niquant le cookie ou autre via un js subtil, mais on a pas forcément envie d'avoir cet effet pour tout les bans... C'était juste pour certains spécimens qui méritent la torture. Donc peut etre encore un autre type de ban...? Ou laisser tomber cette piste...

**Comment by hadware** [comment]
Beh j'sais paw ptet avec une option suplémentaire dans le Json de la commande de ban? Genre si on a "relay_client"=True, on relaie l'information du ban aux clients du trouduc qui s'est fait ban, et donc tu peux déclencher coté client ton arsenal de contremesures.

**Comment by LePetitMarill** [comment]
Why not!
