### ISSUE TITLE
Boire déclenche la commande d'attaque

### ISSUE THREAD

**Issue by haspagan** [loult-elte-fwere/loult-ng#70]
Bonjour,

> /use 0
> Il faut spécifier un nom de pokémon (comme lors d'une attaque),exemple: /use 3 Taupiqueur 2

https://www.doctissimo.fr/html/dossiers/alcool/alcool.htm

**Comment by hadware** [comment]
Je crois voir le problème potentiel, je vais checker ça. Merci pour l'issue.
