### ISSUE TITLE
Ban par cookie

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#8]
Il y a des nuisibles qui sont rapides pour changer d'ip mais qui ne souhaitent pas être random, il serait donc peut être intéressant de les bloquer via cookie. En l'état le ban ip ne sert quasiment à rien.
Est ce que ban par cookie implique forcément base de données ?

Cette issue est plus là pour en discuter que pour formuler une requete. Pas sur que ce soit une bonne solution non plus...

**Comment by hadware** [comment]
Ben c'est à dire que sans base de donnée, le ban sur cookie serait effectif jusqu'à redémarrage du serveur (typiquement, sur le shadowban que je viens d'inplémenter mais que j'ai pas encore pwlepwle, c'est le cas).

J'ai remarqué sur tes suggestions parlent beaucoup de ban. Mrle faut faire attention t'as des dérives autoritaires :^)

**Comment by LePetitMarill** [comment]
Bah oui et non, si tu veux récupérer la bande de cons finis à la pisse sur alphalou, n'hésite pas. On verra pendant combien de temps t'auras la patience de lire des flood avec ton pseudo +fils de pute etc sur le projet qui te prend du temps / des € :D

**Comment by hadware** [comment]
Wesh ça va je rigwlais. Commente plutôt ce que je t'ais dit avant

**Comment by LePetitMarill** [comment]
Ce serait déjà bienw vu qu'on redémarre assez peu en temps normal mais oui pas idéal en effet.
Je suppose que du coup ça dépend du reste (xp/"compte"/rooms etc) pour déterminer si bdd ou pas
