### ISSUE TITLE
Système de whitelist

### ISSUE THREAD

**Issue by LePetitMarill** [loult-elte-fwere/loult-ng#9]
Le loult a le cancer. La communauté se meurt et les derniers qui s'en occupent en sont à se barrer... J'ai pas spécialement envie d'héberger un truc pour des gens que je n'aime pas et qui ne m'aiment pas non plus. Donc proposition :

Il y a depuis un moment une certaine demande pour des salons visibles publiquement et facilement depuis l'accueil. Si les salons sont "cachés", le fait est que les gens qui en ont l'adresse n'y vont pas, soit par flemme soit par "peur" de rater un truc intéressant(?!) sur le principal. Ce pourrait etre des onglets à la IRC / discord, mais il faut en controler l'accès sinon ça n'apporte rien. Donc adresse du websocket concerné cachée + whitelist controlée par les mods. On peut alors imaginer un /invite <uid> pour donner l'accès à un cookie. Bien sur, le /kick qui va avec. La piste mot de passe / accès basé sur le niveau ne fait que retarder l'arrivée du cancer, comme ça s'est vu dans les différents salons privés durables qui sont maintenant déserts... Il faudra du coup que je modifie le client de façon à afficher plusieurs salons à la fois dans des onglets.

Ce qui me chagrine là dedans c'est qu'on accepte quand meme la présence du cancer en se réfugiant dans un coin. Mais on aurait au moins ça.

**Comment by hadware** [comment]
Beh ça demanderait un travail conséquent (pas forcément parce que c'est dur à implem, mais parce que ça va nécessairement bugger au début et tout).

Je serai plus pour une solution simple du type invitation "secrète", du genre une invit' vers un salon que tu peux envoyer à une seule personne en scred. C'est une solution relativement simple et ça devrait permettre de créer des salons oklm sur lesquels tu peux inviter facilement les gens que tu veux.
Après si ça ça suffit pas (leaks des addresses à répétition), jpeux envisager des salons sur whitelist waih, mais ça sera pas mal chiant à mettre en place coté client.

En tout cas le coup des onglets je pense que c'est beaucoup trop de taff pour toi coté client (et ça dénature un peu l'aspect minimaliste du lou je pense)
